import type { Metadata } from "next";
import { ReactQueryDevtools } from '@tanstack/react-query-devtools';
import "./globals.css";
import Navbar from "@/layouts/navbar/Navbar";
import RecoilRootProvider from "@/providers/RecoilRootProvider";
import QueryProvider from "@/providers/QueryProvider";
import SessionProviderWrapper from "@/providers/SessionProviderWrapper";
import ToastProvider from "@/providers/ToastProvider";
import "react-toastify/dist/ReactToastify.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <RecoilRootProvider>
          <QueryProvider>
            <SessionProviderWrapper>
              <ToastProvider />
              <div className="layout">
                <Navbar />
                {children}
              </div>              
              <ReactQueryDevtools />
            </SessionProviderWrapper>          
          </QueryProvider>
        </RecoilRootProvider>        
      </body>
    </html>
  );
}
