import type { Metadata } from "next";
import { ReactQueryDevtools } from '@tanstack/react-query-devtools';
import "./globals.css";
import Navbar from "@/layouts/navbar/Navbar";
import RecoilRootProvider from "@/provider/RecoilRootProvider";
import QueryProvider from "@/provider/QueryProvider";
import SessionProviderWrapper from "@/provider/SessionProviderWrapper";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <RecoilRootProvider>
          <QueryProvider>
            <SessionProviderWrapper>
              <Navbar />
              {children}
              <ReactQueryDevtools />
            </SessionProviderWrapper>          
          </QueryProvider>
        </RecoilRootProvider>        
      </body>
    </html>
  );
}
